server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:keystore/server-a-keystore.p12
    key-store-password: servera123
    key-store-type: PKCS12
    key-alias: server-a
    trust-store: classpath:keystore/truststore.p12
    trust-store-password: truststore123
    trust-store-type: PKCS12
    client-auth: need

spring:
  application:
    name: server-a
  logging:
    level:
      com.example.servera: DEBUG
      reactor.netty: DEBUG

ssl:
  keystore:
    path: src/main/resources/keystore/server-a-keystore.p12
    password: servera123
  truststore:
    path: src/main/resources/keystore/truststore.p12
    password: truststore123

  b:
    url: https://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always